version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/api-first-client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/api-first-server"
    schedule:
      interval: "weekly"
