name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  verify-project-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projects: [ 'api-first-client', 'api-first-server' ]
    name: ${{ matrix.projects }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0
          distribution: 'adopt'
          java-package: 'jdk'

      - name: Build the project
        working-directory: ${{ matrix.projects }}
        run: mvn clean verify

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: true